### ISSUE TITLE
Settings reset to default if I press "Stop"

### ISSUE THREAD

**Issue by shurupov** [WarhamsterBoo/reactjs-dev#15]
При нажатии на кнопку "Stop", всё не только останавливается, но также сбрасываются ранее выстроенные настройки (X dimension, Y dimansion, Filling percentage). 
Шаги воспроизведения:
1. При запуске изменить настройки.
2. Нажать "Run"
3. Нажать "Stop"
Ожидаемое поведение: Жизнь Конвея останавливается.
Фактическое поведение: Жизнь Конвея останавливается и сбрасываются настройки.

**Comment by WarhamsterBoo** [comment]
Fixed
