### ISSUE TITLE
I can't set percentage by mouse more than 28

### ISSUE THREAD

**Issue by shurupov** [WarhamsterBoo/reactjs-dev#16]
Шаги воспроизведения:
1. Нажать мышкой на кнопочку вверх  в поле ввода Filling Percentage. Держать нажатой несколько секунд и/или нажать много раз.
Ожидаемое поведение: значение возрастёт до 100.
Фактическое поведение: значение возрастает до 28 и выше не растёт.

Тем не менее с клавиатуры значение больше 28 ввести можно.

**Comment by WarhamsterBoo** [comment]
Fixed
