### ISSUE TITLE
Field is filled by alive cells only one time if percentage is not changed.

### ISSUE THREAD

**Issue by shurupov** [WarhamsterBoo/reactjs-dev#19]
Шаги воспроизведения:
1. Устанавливаем нужные ширину, высоту и процент заполнения.
2. Жмём Apply.
3. Увеличиваем ширину и высоту. Процент не трогаем!
4. Жмём Apply.
Ожидаемое поведение: поле раздвинется и заполнится живими ячейками заново.
Фактическое поведение: поле раздвинется, но не заполнится. Новые ячейки справа и снизу останутся пустыми.

**Comment by WarhamsterBoo** [comment]
Fixed
